### ISSUE TITLE
DEI Committee Charter

### ISSUE THREAD

**Issue by marthacryan** [jupyter/executive-council-team-compass#6]
I created a PR to add the DEI Committee charter to the governance repo: https://github.com/jupyter/governance/pull/160 and received some feedback but I wanted to check in here to see if anyone else had feedback. I was also wondering about the next steps - would taking the PR out of draft trigger a vote?

**Comment by blink1073** [comment]
Thanks for the prompt @marthacryan!  Since the referenced PR is scheduled to be merged today, I'll close this issue.
